# Generated by Django 2.1.4 on 2019-02-13 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('publish_on', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('categories', models.ManyToManyField(related_name='products', to='categories.Category')),
                ('tags', models.ManyToManyField(related_name='products', to='tags.Tag')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
